-- MySQL Script generated by MySQL Workbench
-- dim. 30 déc. 2018 02:23:18 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tfjm-signin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tournoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tournoi` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `begin_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `description` TEXT NULL,
  `limit_date_signin` DATETIME NULL,
  `limit_date_def` DATETIME NULL,
  `limit_date_nds` DATETIME NULL,
  `max_team_validees` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `trigramme` VARCHAR(45) NOT NULL,
  `password` NVARCHAR(550) NOT NULL,
  `id_tournoi` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teams_tournoi1_idx` (`id_tournoi` ASC),
  CONSTRAINT `fk_teams_tournoi1`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `tournoi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `participants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `nom_resp` MEDIUMTEXT NULL,
  `date_naissance` DATE NULL,
  `sexe` TINYINT NULL,
  `code_postal` INT NULL,
  `adresse` TEXT NULL,
  `participants` TEXT NULL,
  `ville_etabl` VARCHAR(255) NULL,
  `nom_etabl` VARCHAR(255) NULL,
  `classe` VARCHAR(45) NULL,
  `coord_resp` TEXT NULL,
  `team` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_participants_teams1_idx` (`team` ASC),
  CONSTRAINT `fk_participants_teams1`
    FOREIGN KEY (`team`)
    REFERENCES `teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encadrants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encadrants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `profession` VARCHAR(255) NULL,
  `presence` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organisateurs` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tournoi_has_organisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tournoi_has_organisateurs` (
  `id_tournoi` INT UNSIGNED NOT NULL,
  `id_organisateur` INT NOT NULL,
  PRIMARY KEY (`id_tournoi`, `id_organisateur`),
  INDEX `fk_tournoi_has_organisateurs_organisateurs1_idx` (`id_organisateur` ASC),
  INDEX `fk_tournoi_has_organisateurs_tournoi_idx` (`id_tournoi` ASC),
  CONSTRAINT `fk_tournoi_has_organisateurs_tournoi`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `tournoi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournoi_has_organisateurs_organisateurs1`
    FOREIGN KEY (`id_organisateur`)
    REFERENCES `organisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teams_has_encadrants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teams_has_encadrants` (
  `id_team` INT NOT NULL,
  `id_encadrant` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_team`, `id_encadrant`),
  INDEX `fk_teams_has_encadrants_encadrants1_idx` (`id_encadrant` ASC),
  INDEX `fk_teams_has_encadrants_teams1_idx` (`id_team` ASC),
  CONSTRAINT `fk_teams_has_encadrants_teams1`
    FOREIGN KEY (`id_team`)
    REFERENCES `teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_has_encadrants_encadrants1`
    FOREIGN KEY (`id_encadrant`)
    REFERENCES `encadrants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
